pipeline:
  build:
    image: python:3.5.2
    environment:
      # I use dj_database_url to specify my DB settings
      - DATABASE_URL=postgres://postgres@localhost
    commands:
      - sleep 5 # (probably not necessary)
      - pip3 install -r requirements.txt
      - cd personal_website
      - python ./manage.py test
      - cd ..
    when:
      branch: [ master ]
      event: [push, pull_request] # trigger step on push and pull events
publish:
  image: plugins/docker
  username: ${DOCKER_USERNAME}
  password: ${DOCKER_PASSWORD}
  email: 11825744+ahuyen@users.noreply.github.com
  repo: ahuyen/personalwebsite
  tag: latest
  file: Dockerfile
  environment:
    - DOCKER_LAUNCH_DEBUG=true
  when:
    branch: [ master ]
    event: [ push ]
services:
  database:
    image: postgres
    environment:
      - DATABASE_URL=postgres://postgres@localhost